name: build & push

env:
  IDE_VERSION: "2023.1"

on:
  workflow_call:
    inputs:
      IDE:
        required: true
        type: string
      IDE_SHORT:
        required: true
        type: string
      IDE_CODE:
        required: true
        type: string
      IDE_VERSION:
        required: false
        type: string
        default: "2023.1"
    secrets:
      username:
        required: true
      token:
        required: true
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Set build-args
        run: |-
          IDE_INPUT_VERSION="$(echo ${{ input.IDE_VERSION }}"
          if [ "${IDE_INPUT_VERSION}" != '' ]; then
            echo "IDE_VERSION=${IDE_INPUT_VERSION}" | tee /dev/stderr >> $GITHUB_ENV;
          else
            echo "IDE_VERSION=${IDE_VERSION}" | tee /dev/stderr >> $GITHUB_ENV;
          fi
      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ./image
          platforms: linux/amd64,linux/arm64
          build-args: |
            IDE=${{ inputs.IDE }}
            IDE_SHORT=${{ inputs.IDE_SHORT }}
            IDE_CODE=${{ inputs.IDE_CODE }}
            IDE_VERSION=${{ inputs.IDE_VERSION }}
          tags: |
            rollupdev/indexer:${{ inputs.IDE_SHORT }}-${{ inputs.IDE_VERSION }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
