name: run workflows for all IDEs

on:
  workflow_dispatch:
    inputs:
      IDE_VERSION:
        description: "IDE Version to build"
        required: true
        type: string
        default: "2023.1"
jobs:
  build-intellij:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: ideaIU
      IDE_SHORT: idea
      IDE_CODE: idea
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-webstorm:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: WebStorm
      IDE_SHORT: webstorm
      IDE_CODE: webstorm
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-goland:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: goland
      IDE_SHORT: goland
      IDE_CODE: go
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-pycharm:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: pycharm-professional
      IDE_SHORT: pycharm
      IDE_CODE: python
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-phpstorm:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: PhpStorm
      IDE_SHORT: phpstorm
      IDE_CODE: webide
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-clion:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: CLion
      IDE_SHORT: clion
      IDE_CODE: cpp
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-rubymine:
    uses: dockergiant/jetbrains-indexer/.github/workflows/build-and-push.yaml@master
    with:
      IDE: RubyMine
      IDE_SHORT: rubymine
      IDE_CODE: ruby
      IDE_VERSION: ${{ inputs.IDE_VERSION }}
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
